### ISSUE TITLE
Erro: Notice: Undefined index

### ISSUE THREAD

**Issue by luiz-andrade** [satellasoft/OpenTask#1]
Bom Dia

Na tela inicial está apresentando o erro abaixo:

> Notice: Undefined index: p in D:\laragon\www\OpenTask\App\View\layout\partials\menu-mobile.php on line 16

**Comment by satellasoft** [comment]
Bom dia, Luiz.
Ainda falta finalizar a nossa documentação, mas você precisa ajustar:
- https://github.com/satellasoft/OpenTask/blob/master/.htaccess
Na linha **RewriteRule ^((?!public/).*)$ opentask/public/$1 [L,NC]**,  troque o opentask/ pela pasta/dir que seu projeto se encontra. Se estiver na root, deixe apenas public/

- https://github.com/satellasoft/OpenTask/blob/master/App/Config/config.php
**Linha 3 define("BASE", "/opentask/");** - O diretório para seu projeto, se estiver na root, deixe **/**.

Nas linhas 5 e 6, é o filtro da sua URL, você pode passar true na linha 6 para ver como está retornando, e então, na linha 5, você coloca a quantidade de índices que necessita ser removido para filtrar as urls, para testar, coloca na barra de endereço: controller/mothod/params. O número de índices removidos tem que devolver essa estrutura, e não: opentask/controller/method/params1...

Estamos finalizando uma nova atualização, após isso, vamos retomar a documentação.

Abraços.

define("URI_UNLINK_COUNT", 2);
define("URI_DEBUG", false);//change to false after test

**Comment by luiz-andrade** [comment]
Fiz as alterações, mas em `http://opentask.test/controller/mothod/params`
 está retornando: 

> Array
> (
>     [0] => mothod
>     [1] => params
> )

**Comment by satellasoft** [comment]
Qual o seu valor para **define("URI_UNLINK_COUNT", 2);**?

**Comment by luiz-andrade** [comment]
> Qual o seu valor para **define("URI_UNLINK_COUNT", 2);**?

Está o padrão 2
[Ver print](https://prnt.sc/re9fic)

**Comment by satellasoft** [comment]
Como você está rodando na root, troque para 1 e faça o teste.

**Comment by luiz-andrade** [comment]
/controller/mothod/params agora retorna isso
> Array
(
    [0] => controller
    [1] => mothod
    [2] => params
)

**Comment by satellasoft** [comment]
Isso mesmo, desativa o debug e tenta rodar novamente.

**Comment by luiz-andrade** [comment]
Muito obrigado @satellasoft  funcionou corretamente.

Parabéns  pelo sistema, ainda não usei mas aparentemente parece muito bom.

**Comment by satellasoft** [comment]
Conseguiu rodar o banco de dados, criar o usuário de primeiro acesso?

Que bom que gostou!  

Em breve vamos implementar um sistema de relatórios...já implementamos várias outras coisas, afinal, estamos utilizando ele em um outro projeto, então conforme as necessidades, novas implementações estão sendo feitas.

**Comment by luiz-andrade** [comment]
> Conseguiu rodar o banco de dados, criar o usuário de primeiro acesso?
> 
> Que bom que gostou!
> 
> Em breve vamos implementar um sistema de relatórios...já implementamos várias outras coisas, afinal, estamos utilizando ele em um outro projeto, então conforme as necessidades, novas implementações estão sendo feitas.

Sim, consegui rodar. Obrigado
