### ISSUE TITLE
Erro ao acessar projeto

### ISSUE THREAD

**Issue by Dev-Henrique-FrontEnd** [satellasoft/OpenTask#3]
Quando clica para acessar o projeto aparece o seguinte erro
`Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't.tk_completed' in 'field list' in C:\xampp\htdocs\tarefas\App\Core\Model.php:123 Stack trace: #0 C:\xampp\htdocs\tarefas\App\Core\Model.php(123): PDO->prepare('SELECT t.id, t....') #1 C:\xampp\htdocs\tarefas\App\Model\TaskModel.php(105): App\Core\Model->ExecuteQuery('SELECT t.id, t....', Array) #2 C:\xampp\htdocs\tarefas\App\Controller\ProjectController.php(150): App\Model\TaskModel->getAllResumed(4, 25, 1) #3 [internal function]: App\Controller\ProjectController->myProject() #4 C:\xampp\htdocs\tarefas\App\Core\Core.php(84): call_user_func_array(Array, Array) #5 C:\xampp\htdocs\tarefas\App\View\index.php(29): App\Core\Core->RunContent() #6 C:\xampp\htdocs\tarefas\App\Core\Core.php(46): require_once('C:\\xampp\\htdocs...') #7 C:\xampp\htdocs\tarefas\Public\index.php(16): App\Core\Core->Run() #8 {main} thrown in C:\xampp\htdocs\tarefas\App\Core\Model.php on line 123`

**Comment by montenegr7** [comment]
Este erro ja foi reparado?? 

A mim, não me aparece e acabei de testar.

**Comment by satellasoft** [comment]
Provavelmente a instalação do Banco não é completa, por isso do erro.

**Comment by montenegr7** [comment]
É melhor fechar esta issue

**Comment by satellasoft** [comment]
Problema aparentemente resolvido.
